### ISSUE TITLE
error while compiling  in Windows

### ISSUE THREAD

**Issue by tibinlukose** [rbaron/omr#1]
Traceback (most recent call last):
  File "omr.py", line 251, in <module>
    main()
  File "omr.py", line 234, in main
    answers, im = get_answers(args.input)
  File "omr.py", line 189, in get_answers
    contours = get_contours(im)
  File "omr.py", line 27, in get_contours
    image_gray, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
ValueError: need more than 2 values to unpack

**Comment by rbaron** [comment]
Hi @tibinlukose. Did you get it to work? I think the actual problem is the OpenCV version. I used opencv-3.1.0.

**Comment by tibinlukose** [comment]
It's fixed,, if possible kindly provide a documentation about customising,

**Comment by Usman590** [comment]
Dear Sir I am facing problem when I give some sheet other then sample give in project How I fix this kindly guide me

**Comment by huydophu** [comment]
I get this error!! Please guide me. Thank you so much.
 File "omr.py", line 251, in <module>
    main()
  File "omr.py", line 234, in main
    answers, im = get_answers(args.input)
  File "omr.py", line 199, in get_answers
    for i, q_patch in enumerate(get_question_patches(transf)):
  File "omr.py", line 139, in get_question_patches
    for i in xrange(1, 11):
NameError: name 'xrange' is not defined

**Comment by rbaron** [comment]
@Usman590 please refer to #4 .

@huydophu it seems like you might be using python 3 instead of python 2.

**Comment by srbhrthr** [comment]
Same error but not resolving after upgrading opencv to 4.0.0.21
