### ISSUE TITLE
calculating the corner feat

### ISSUE THREAD

**Issue by LeoEzhil** [rbaron/omr#16]
Could you explain how to get corner feats

**Comment by rbaron** [comment]
Hi @LeoEzhil,

(CORNER_FEATS)[https://github.com/rbaron/omr/blob/master/omr.py#L7] is a list of features as if you had applied the function (get_features)[https://github.com/rbaron/omr/blob/master/omr.py#L60] to the corner's contour.

Let me know if that helps.

**Comment by LeoEzhil** [comment]
Thanks for your update.
Just to clarify, how we got the corner feat list, it's a hard code value.
Do we any functions to get those values. If I have different omr with
corner mark how should I calculate it?

Regards,
Leo

**Comment by rbaron** [comment]
Hi @LeoEzhil,

you can load up any contour you like (you can use the `get_contours` function on an image containing just the shape you want for convenience). This function returns a list of contours. Once you select the contour you want from that list (the outermost contour of your shape -- you can draw a line over the contour to make sure it's the right one), you can call the `get_features` function on it. You will get something like `CORNER_FEATS` for your shape.

**Comment by rbaron** [comment]
Hi @LeoEzhil,

I just refactored the code and now the corner features are explicitly calculated at runtime. I believe  that will make it clearer how the old magical numbers came to be.

Please feel free to re-open this issue in case you have more questions.
