### ISSUE TITLE
90% fail rate on scanned sheet.pdf

### ISSUE THREAD

**Issue by RidaAyed** [rbaron/omr#22]
Nice work, thank you. Maybe you can see something I missed while testing with the scanned [sheet.pdf](https://github.com/rbaron/omr/blob/3d4b7dd53b272b195e872663673fb6098976dcd7/sheet/sheet.pdf)

```sh
$ python omr.py --input ./scan_2022-01-07-162351_001.jpg  --output /tmp/results.png --show

Q1: A
Q2: C
Q3: C
Q4: E
Q5: N/A
Q6: N/A
Q7: A
Q8: N/A
Q9: N/A
Q10: N/A
```
scan_2022-01-07-162351_001.jpg (using sheet.pdf):
![scan_2022-01-07-162351_001](https://user-images.githubusercontent.com/20554483/148569315-ac08c579-010a-4680-a43e-4a19fbceee51.jpg)

results.png
![results](https://user-images.githubusercontent.com/20554483/148569378-cd5e6a4e-74c3-4c3f-8fcf-d6fadf6b68a4.png)

**Comment by yunustalip** [comment]
i have the same problem

**Comment by rbaron** [comment]
There is a super simple heuristic for invalidating when there are two marked alternatives on the same row [here](https://github.com/rbaron/omr/blob/master/omr.py#L254):

```Python
    if sorted_means[0]/sorted_means[1] > .7:
        return None
```

If you don't care about detecting this, you can just comment out the lines, and then you'll get the expected result:

<img width="510" alt="image" src="https://user-images.githubusercontent.com/1573409/210000160-0fd721e2-8045-4320-9128-14eb61ec5754.png">

If you care about catching this type of errors, you'll need to tweak this parameter to fit your use case. Keep in mind that this is a simple script for educational purposes - a more robust model would be ideal for a real world application.
