### ISSUE TITLE
How Other Then sample sheet be evaluated

### ISSUE THREAD

**Issue by Usman590** [rbaron/omr#3]
Dear Sir I am facing problem when I give some sheet other then sample give in project How I fix this kindly guide me. Suppose  I want to evaluate 100 number of question sheet. And It Produce correct result only when diagonal sample page given to it he I fix it?

**Comment by rbaron** [comment]
hi @Usman590. We're discussing a related isse at #4 . I'm closing this, but please feel free to join in on the other issue. 👍
