### ISSUE TITLE
Sample data should be used as unit tests

### ISSUE THREAD

**Issue by scls19fr** [rbaron/omr#9]
Hello,

https://github.com/rbaron/omr/tree/master/img provide sample data
maybe this kind of data could be used as unit tests.

Best regards

**Comment by scls19fr** [comment]
Here is a possible test case:

```python
import os
from omr import get_answers


def test_omr():
    answers = get_answers(os.path.join("img", "answered-sheet-photo.jpg"))
    assert answers[0] == ['A', 'C', 'C', 'E', 'N/A', 'N/A', 'A', 'N/A', 'N/A', 'N/A']
```

Enabling continuous integration with Travis (for example) could be an other interesting feature to have.

**Comment by rbaron** [comment]
Thanks for the idea and the pull request (#11). We'll keep the conversion going on the PR!
